module.exports.UserService = require('./user.service')
module.exports.appointmentService = require('./appointment.service')
module.exports.questionService = require('./question.service')
module.exports.feedbackService = require('./feedback.service')
module.exports.TokenService = require('./token.service')
module.exports.AuthService = require('./auth.service')
