module.exports.User = require('./user.model')
module.exports.Appointment = require('./appointment.model')
module.exports.Feedback = require('./feedback.model')
module.exports.Question = require('./question.model')
module.exports.Token = require('./token.model')
